name: Jira Update Issue
description: Update Jira issue with service version
inputs:
  issue:
    description: Key of the issue to be updated
    required: true
  comment:
    description: Comment
    required: true
runs:
  using: 'node12'
  main: './index.js'
